### PR TITLE
Added missing jna to eclipse project, netbeans project and ant

### PR DESCRIPTION
**Pull request by soywiz**

### CODE REVIEW

**Comment by soywiz** [comment]
BTW. The whole build system seems pretty complex : eclipse project, netbeans project + ant + embedded libs. Are you using all those IDEs for an specific reason? Lately I'm just using gradle + intelliJ community edition for all my projects and it keeps pretty simple (I just have a single `build.gradle` file to open the project and to build/do other custom tasks)

**Comment by georgemoralis** [comment]
actually we use ant for the autobuild bot (using build_auto.xml) . I have tried intelliJ  the issue i have is which idea generate files should be under git or not, that's an open issue in idea still...

**Comment by soywiz** [comment]
I'm using idea and intelliJ allows to open build.gradle, it generates `.iml`, `.ipr` or `.iws` files / `.idea` folder (that I have already added to `.gitignore`). You do notneed to include them; you just need the `build.gradle` file to be able to open the project on idea. And intelliJ productivity is much greater to any other IDE i have tried for java/kotlin.

**Comment by georgemoralis** [comment]
not familiar to gradle, i will take a look at it

**Comment by soywiz** [comment]
A brief introduction to gradle:

Gradle replaces ANT + Maven. It has maven facilities for dependency resolving and downloading and base conventions, but allow to create custom tasks.  Tasks are not xml-based but groovy based. I do not like groovy at all, and gradle starts supporting kotlin with build.gradle.kts already. At any rate there are snippets out there to do stuff, so usually gradle just sits there and you can use it transparentely within intelliJ as a project file but allowing you to build stuff from terminal and add custom tasks.
Gradle is being used in lot of places including intelliJ, Android (+ Android Studio) and Unity . It is not used just for Java but anything, including C++. So it is pretty common nowadays so it is worth using it.

If you like the idea and end using gradle we could get rid of lib folder + nbproject folder + .project and .classpath files + the ant build.xml after adding the required tasks. And that would mean that updating to a new version of a library could mean updating just a number in build.gradle once. No binaries. No changing numbers in several places which is pretty cool.

**Comment by hlide** [comment]
Hi soywiz,

it was a long time I didn't touch Java. The last time I did, it was with NetBean I think. If you think you can make things simpler with Gradle, it would be great as long as gid15 is okay (he is now the main developer who contributes the most). I do have a question regarding intelliJ: is that free to download and use?

**Comment by soywiz** [comment]
@hlide Sure intelliJ has two versions: Ultimate (as a poliglot IDE) and community (that is opensource and has less features but has complete and great java and kotlin support)

* https://github.com/JetBrains/intellij-community
* https://www.jetbrains.com/idea/#chooseYourEdition

And as mater of fact, lots of IDEs like Android Studio are based on the intellij-community edition. So no problems with that.

**Pull request merged**
