### PR TITLE
Configure for netbeans 12.0

### PR DESCRIPTION
**Pull request by FollowerOfBigboss**
This pr edits some configuration files for netbeans. It removes some dropped dependencies and adds some jars which is required for compilation and tests.  I tried to make it usable for freshly installed netbeans 12.0 and jdk8 installations. I will leave it as draft because i want to see how other systems react to changes.

### CODE REVIEW

**Comment by gid15** [comment]
Should I merge this draft pr? I'm not using netbeans myself.

**Comment by FollowerOfBigboss** [comment]
I wanted to upgrade latest netbeans but unfortunately latest versions doesn't recognize current project format(old project format deprecated?) so i upgraded it to most recent version of netbeans which works. It functions well in netbeans 12.0, debugger and all kinds of thing works perfectly. I think i should come up with more acceptable solution. I propose this as a workaround. Can you share your configuration? So i can configure and document it for newcomers. Yeah that' s all. If you feel good with it then merge it.

**Comment by mrcmunir** [comment]
> I wanted to upgrade latest netbeans but unfortunately latest versions doesn't recognize current project format(old project format deprecated?) so i upgraded it to most recent version of netbeans which works. It functions well in netbeans 12.0, debugger and all kinds of thing works perfectly. I think i should come up with more acceptable solution. I propose this as a workaround. Can you share your configuration? So i can configure and document it for newcomers. Yeah that' s all. If you feel good with it then merge it.

Yes the old project format it's deprecated you will needed update build.gradle for that.
https://github.com/jpcsp/jpcsp/blob/master/build.gradle

**Comment by FollowerOfBigboss** [comment]
> > I wanted to upgrade latest netbeans but unfortunately latest versions doesn't recognize current project format(old project format deprecated?) so i upgraded it to most recent version of netbeans which works. It functions well in netbeans 12.0, debugger and all kinds of thing works perfectly. I think i should come up with more acceptable solution. I propose this as a workaround. Can you share your configuration? So i can configure and document it for newcomers. Yeah that' s all. If you feel good with it then merge it.
> 
> Yes the old project format it's deprecated you will needed update build.gradle for that. https://github.com/jpcsp/jpcsp/blob/master/build.gradle

Yeah i have plans to touch gradle build but not for now because i feel it will take longer than i think.

**Pull request merged**
