### PR TITLE
Updates for English and Japanese Language Files

### PR DESCRIPTION
**Pull request by DragonNeos**
This update should correct typos that were left in the English file and allow Japanese to be displayed with actions regarding to SAVEDATA. However, SAVEDATA messages will only appear with Japanese characters if the user chooses Japanese in the Language Menu. Otherwise, those who use Jpcsp in English will not be able to see Japanese games displaying SAVEDATA messages with Japanese characters.

It would be nice if Jpcsp could detect a loaded game's language and display messages (such as SAVEDATA) in that language without having to change the language of the emulator's GUI. A PSP could load a Japanese game and display messages in Japanese, but once the user exits the game the XMB is still in the language that they set it to (ex: Chinese).

With regards to SAVEDATA messages in Japanese, some messages (like the question shown in the image below) are aligned a little too far to the left or right.
ucjs10110-shot-1
Could Jpcsp have a conditional clause for SAVEDATA where English games display "X Enter" and "O Back" and Japanese games inverse the text and display "X 戻る" (Back) and "O 決定" (Enter)? I know there is an option to choose which button can be used for Enter, but the text seems to be coded so that Enter is always shown on the left and Back is always shown on the right.

An issue that came up while testing the edited entries in Japanese was how certain text gets displayed. In English, you can have this:
```
sceUtilitySavedata.SAVE=Save
sceUtilitySavedata.strCompleted.text=completed
```
In Jpcsp, this gets displayed as:
```
Save completed.
```
The period gets added automatically. However, this wouldn't work in languages such as Chinese or Japanese since they use this character (。) instead to end a sentence. In this case, for Japanese:
```
sceUtilitySavedata.SAVE=\u30bb\u30fc\u30d6
sceUtilitySavedata.strCompleted.text=\u304c\u5b8c\u4e86\u3057\u307e\u3057\u305f\u3002
```
In Jpcsp, this gets displayed as:
ucjs10110-shot-2
As you can see, the text gets displayed as セーブ が完了しました。 .
The correct way to display this message would be as セーブが完了しました。 (without the space after the third character and period that appears after the sentence)

For SAVEDATA, it would probably be better if each message had its own unique text string instead of being composed of two lines as seen in the case above. Jpcsp doesn't contain all possible messages for SAVEDATA in the language files as entries like Saving/Loading/Deleting Please wait... are missing.

### CODE REVIEW

**Comment by Hykem** [comment]
@gid15 I'm merging this now, but please review @DragonNeos suggestions.

**Comment by gid15** [comment]
Suggested changes should now be implemented in d2ecdd8. Please check the Japanese translations as I just made copy&paste without understanding the meaning...

**Comment by gid15** [comment]
About the incorrect position of the some messages, could you post a screenshot from a real PSP for comparison?
Thank you!

**Comment by DragonNeos** [comment]
@gid15 I checked the Japanese translations for the lines that you copied and pasted into the language file and they are correct. Ignore the screenshots in my previous post since they were made at 2x resolution (960x544) on Jpcsp. Compare the screenshots between the PSP and Jpcsp d2ecdd8 (using PSP Font) below:

PSP
ucjs10110_0000

Jpcsp
ucjs10110-shot-1

The first thing you probably notice is the alignment of the question データをセーブしますか？ (Do you want to save this data?). It should be more centered. The choices はい (Yes), いいえ (No), X 戻る (Back), and O 決定 (Enter) might need to shift a few pixels to the left. The area between the two horizontal lines should be more compressed and the selection box for each choice should be centered in alignment. Despite using the same font for Jpcsp, the font seems to be larger in display.

In some cases when the PSP doesn't detect any SAVEDATA for a game, it will display a generic ICON0.PNG (not every game contains a No Data ICON0.PNG). On the PSP, the ICON0.PNG will illuminate every few seconds. Towards the bottom left, the text being displayed is slightly different between the PSP and Jpcsp. For the PSP, the text is 新しいセーブデータ (New Save Data). On Jpcsp, the text is セーブデータ (Save Data). The PSP displays the size of the SAVEDATA as 544 KB while Jpcsp shows the size of the SAVEDATA as 512 KB (difference of 32 KB).

PSP
ucjs10110_0001

As I mentioned in my last post, Jpcsp doesn't have SAVEDATA text entries for messages that occur in transition for each action (Save, Load, Delete). The usual process for SAVEDATA on a PSP once confirming the action is to display Saving/Loading/Deleting Please wait... (appears for 1-2 seconds) then show Save/Load/Delete completed.

PSP
ucjs10110_0002

Jpcsp
ucjs10110-shot-2

The text セーブが完了しました。 (Save completed.) should be closer to the left. The biggest difference between these two screenshots is the Date & Time Format. On both the PSP and Jpcsp. I set the Date & Time Format to use MM-DD-YYYY and 12H. However, the results were completely different as Jpcsp seems to ignore any set formats and defaults to YYYY-MM-DD and 24H.

PSP
npjh50660_0002

Jpcsp
npjh50660-shot-1

As you can see, the text データがありません。 (There is no data.) is way off on Jpcsp. The text should be in the middle of two horizontal lines.

PSP
npjh50660_0000

Jpcsp
npjh50660-shot-2

The main difference other than the Date & Time Format is that the size of the SAVEDATA should be shown next to the Time (missing on Jpcsp).

PSP
npjh50660_0001

Jpcsp
npjh50660-shot-3

It would be nice if a similar method used in 8c98c0a could be applied to sceUtilitySavedata mode=LISTLOAD and sceUtilitySavedata mode=LISTDELETE. @lightfirst mentioned in his post (http://www.emunewz.net/forum/showthread.php?tid=168494&pid=221169#pid221169) that some screens don't appear when deleting SAVEDATA. When deleting SAVEDATA, remaining Memory Stick (possibly calculate Hard Drive space for Jpcsp) capacity should be shown in the upper right corner in MB. There should be a confirmation screen for deleting SAVEDATA (This save data will be deleted. Are you sure you want to continue?). Once the user presses Enter, the screen should then show Delete completed.

PSP
uljm06097_0001

Jpcsp
uljm06097-shot-2

It seems that Jpcsp is inconsistent when the emulator encounters a game without any SAVEDATA in the case of sceUtilitySavedata mode=LISTSAVE (Bleach Heat The Soul 7 used its own ICON0.PNG while Musou Orochi 2 Special used the generic ICON0.PNG).

**Comment by gid15** [comment]
Thank you for the research and the very useful screenshots!
The described changes should now be implemented in 4098f5d, excepted for the delete mode.

**Pull request merged**
