### PR TITLE
Using Resource Han Rounded font as a default jpn0.pgf font

### PR DESCRIPTION
**Pull request by lightfirst**
from https://github.com/CyanoHao/Resource-Han-Rounded

Resource-Han-Rounded
NPJH50107-Shot-1

SourceHanSans
NPJH50107-Shot-2

jpn0.pgf from real psp
NPJH50107-Shot-3

### CODE REVIEW

**Comment by sum2012** [comment]
No , I does not support traditional chinese (繁体字)

**Comment by sum2012** [comment]
Sorry @lightfirst 
Check my real psp , the font also have problem
https://ibb.co/t8PD92j
https://ibb.co/Wk8DTCK

**Comment by lightfirst** [comment]
If I guess correctly, this Chinese patch game using costom character table

**Comment by gid15** [comment]
What is the result? Should this Pull request be merged?

**Comment by sum2012** [comment]
i think can merge
在 2020年11月19日週四 上午5:54，gid15 <notifications@github.com> 寫道：

**Pull request merged**
