### PR TITLE
Added gradle support

### PR DESCRIPTION
**Pull request by soywiz**
Added a library unpacker so it is no longer needed to set the path of native libraries. It would allow to create fatjars and launch4j with a single file.

### CODE REVIEW

**Comment by soywiz** [comment]
Now you can execute `gradlew run` and it will compile + run jpcsp without any special IDE requirement

**Comment by soywiz** [comment]
@gid15 have you tried to import build.gradle in eclipse? I added JNA library for windows native Battery stuff (and do not added it to the `lib` folder but instead referenced from maven central) and not updated eclipse project, so the eclipse project should not work by now.
Try if you can open it with build.gradle, and I can make another PR deleting old eclipse project files + lib folder (but the asm library that I was not able to find on central in the 4.0-RC1 version)

**Comment by georgemoralis** [comment]
it might be good to have it on lib folder since it is used in netbeans project as well..

**Comment by soywiz** [comment]
Ok. I'm going to do another PR with that.
I have seen that in order to use gradle with eclipse: http://stackoverflow.com/questions/10722773/import-existing-gradle-git-project-into-eclipse

There is a gradle plugin that autogenerates the eclipse project based on build.gradle, so syncing is as easy as doing `gradle eclipse`. I'm going to install eclipse and netbeans and test it, and I will include jna in the lib folder too.

**Pull request merged**
