### PR TITLE
Fix for Aces of War (Europe) freezes up after chapter selection

### PR DESCRIPTION
**Pull request by sum2012**
The compiled jar file:
[jpcsp.zip](https://github.com/jpcsp/jpcsp/files/13062215/jpcsp.zip)

I don't know that how to limit the change to that game only

### CODE REVIEW

**Comment by ANR2ME** [comment]
Btw, `noDelayTimings` not supposed to have delays isn't?

**Comment by sum2012** [comment]
Yes,I did not know that I test wrong

**Review by gid15 — APPROVED** [review]

**Comment by ANR2ME** [comment]
You probably want to adjust the delay on `sceIoRead` too :)

**Comment by sum2012** [comment]
@gid15 My last finding is only changing sceIoRead timing, file size / 4.2 ,I don't know how to code it.

**Pull request merged**
