### PR TITLE
Fix "Akaya Akashiya Ayakashi no" and "Dies irae Amantes amentes" UMD switch

### PR DESCRIPTION
**Pull request by sum2012**
A small note that the logic is not same as ppsspp fix https://github.com/hrydgard/ppsspp/pull/9245
Anyway , jpcsp modify log: https://gist.github.com/sum2012/a5545cdf988c67f748e6130fc1203a13

### CODE REVIEW

**Comment by sum2012** [comment]
Happy year of the rooster!

**Comment by sum2012** [comment]
DO NOT MERGE

This make another game "Dies irae Amantes amentes ULJM06107 " get stuck in loading sceUmdCheckMedium keep returning 0x0

**Comment by sum2012** [comment]
I have fixed ppsspp side
https://github.com/hrydgard/ppsspp/pull/9256
But I am too tried,jpcsp side will be fixed

**Comment by gid15** [comment]
Happy New Year!

**Comment by sum2012** [comment]
@gid15 now you can review and merge :)
Dies irae Amantes amentes switch umd modify log: https://gist.githubusercontent.com/sum2012/322d9bac59b27746da2be083903da63a/raw/766e23014c3c8704b4a2b334b2e6f35fee92cc97/gistfile1.txt

**Comment by gid15** [comment]
This seems to be quite a complicated logic. Is it not simply that the iso should be removed during a short time (e.g. half a second) to simulate the removing of the UMD before the insertion of a new one?
So that an application polling for sceUmdCheckMedium() will receive 1, then 0 for half a second, then 1 again with the new iso?

**Comment by sum2012** [comment]
For " Akaya Akashiya Ayakash" ,this have finish.
For "Dies irae Amantes amentes",it needs sceUmdWaitDriveStatCB and sceUmdGetDriveStat return PSP_UMD_NOT_PRESENT during removing of the UMD

**Comment by gid15** [comment]
Right,  sceUmdWaitDriveStatCB() and sceUmdGetDriveStat() would automatically return PSP_UMD_NOT_PRESENT when there is no iso (i.e. during the half second switch).
Are you working on such a change, as this is your idea? Or should I make it?

**Comment by sum2012** [comment]
This change is ready to merge.
But you can make it for simple (Use event to change sceUmdCheckMedium 's value ,I tried that but fail )

**Pull request closed without merging**
