### PR TITLE
Reduce Unknown video command  log level

### PR DESCRIPTION
**Pull request by sum2012**
Mega Man Powered Up ULUS10091 call often,reduce performance

### CODE REVIEW

**Comment by sum2012** [comment]
I can change to log once

**Comment by sum2012** [comment]
@gid15 I can change to log once

**Comment by gid15** [comment]
Sorry for later reply. I was thinking to count how many times such a WARN has been generated and only log e.g. the first 5 times, than display a summary when leaving Jpcsp how many times it has been generated.

**Comment by gid15** [comment]
I think that 75aefc4 would help to reduce the performance impact and still keep logging of such unknown commands

**Pull request closed without merging**
