### PR TITLE
Tests

### PR DESCRIPTION
**Pull request by soywiz**
I feel a bit sorry for spamming that much with PRs. Can I have write access to the repo so I can push code directly?

### CODE REVIEW

**Comment by georgemoralis** [comment]
i have added you it should work now

**Comment by soywiz** [comment]
Going to check asap. Have you reopened eclipse project? I modified .classpath file with:
```
<classpathentry kind="src" path="resources"/>
```

**Comment by gid15** [comment]
Yes, I see the change of the .classpath in Eclipse

**Comment by soywiz** [comment]
Fixed. It was because I added a too generic .gitignore pattern that prevented adding ScreenshotIcon.png from icons folder.

**Comment by gid15** [comment]
Ok, working again now...

**Pull request merged**
